name: demo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Responsive UI
  flutter_screenutil: ^5.9.3

  # Google font
  google_fonts: ^6.2.1

  # Icons
  material_symbols_icons: ^4.2801.0

  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  go_router: ^15.1.1
  intl: ^0.20.2
  intl_utils: ^2.8.7
  pull_to_refresh_flutter3: ^2.0.2
  shared_preferences: ^2.5.3
  encrypt_shared_preferences: ^0.9.9
  dio: ^5.8.0+1

  #Talker
  talker: ^4.7.5
  talker_flutter: ^4.7.5
  talker_dio_logger: ^4.7.5
  talker_bloc_logger: ^4.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  injectable_generator:
  flutter_gen_runner:

flutter_gen:
  output: lib/resources/
  line_length: 100 # Optional (default: 80)

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

flutter_intl:
  enabled: false
